#!/usr/bin/env bash
# This script transfers a file  from a client to a server
# Accepts 4 parameters:
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses

  if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1

  fi
     file_path=$1
     server_ip=$2
     user=$3
     path_to_private_key=$4

scp -o StrictHostKeyChecking=no -i "$path_to_private_key" "$file_path" "$user@$server_ip":~/
