#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect  requirements below:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# it must return a page that contains the string Hello World! when queried at its root using curl
# You can’t use systemctl for restarting nginx

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx stop
sudo service nginx start
