#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect  requirements below:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# Configured so that /redirect_me is directing to another page
# The redirection must be a "301 Moved Permanently"
# You can’t use systemctl for restarting nginx

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF'

sudo service nginx stop
sudo service nginx start
