#!/usr/bin/env bash
# A  Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

# Requirements:
# You must use the while loop (for and until are forbidden)
# Note that in this example, we only display the first 70 lines using the head command.

i=0
while [ $i -le 12 ] ;
do
  echo Hour: $i
  j=1

  while [ $j -le 59 ] ;
  do
    echo $j
    ((j++))
  done

((i++))
done
