#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

# Requirements:
# You must use the for loop (while and until are forbidden)
# Do not display hidden files

for file in *
do
  if [ -f "$file" ]
  then
      name_after_first_dash="${file#*-}"
      echo "$name_after_first_dash"
  fi
done
